[package]
name = "deeplx"
version = "0.1.8"
edition = "2021"
authors = [
    "Homing So <i@homing.so>"
]
description = "A Rust package for unlimited DeepL translation"
license = "MIT"
readme = "README.md"
repository = "https://github.com/hominsu/deeplx-rs"
keywords = ["deeplx", "translation"]
categories = ["text-processing", "internationalization"]
exclude = [".*"]

[features]
default = ["proxy"]
proxy = []
impersonate = ["dep:rquest"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytes = { version = "1.9.0" }
rand = { version = "0.8" }
chrono = { version = "0.4" }

brotli = { version = "7" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

isolang = { version = "2.4.0" }
whatlang = { version = "0.16" }

reqwest = { version = "0.12", features = ["gzip", "brotli", "json"] }
rquest = { version = "0.33", optional = true, features = ["gzip", "brotli", "json"] }

[dev-dependencies]
lazy_static = { version = "1" }
tokio = { version = "1", features = ["macros"] }

[[test]]
name = "translate"
